### PR TITLE
Close #72 and #78: messenger.js tests and 404 fix

### LINKED ISSUE #72: Add command line option to ignore certain clients when reporting batch results
For my development environment, it would be nice to be able to run a single yeti hub with many browsers connected, but be able to pass a pattern or patterns to tell the yeti client to ignore certain browser user agents when reporting results.  For example, I may have one app that supports IE7, but another that doesn't and I don't want the test results from IE7 reported for the latter.  

I propose an argument like `--ignore-agents`, with the value being a pattern (regex) used to filter agents whose results are passed to the reporter.  It might be better to implement the actual ignore processing on the hub so that the tests aren't even run in the ignored agents.

I'll do the work to implement this issue myself if there is a settlement on the api and implementation specifics.

### PR DESCRIPTION
**Pull request by clarle**
Added tests for errors 404 and 405 with vows and pact.

Discovered issue #78 which is a simple logic error in providing the response error code.

### CODE REVIEW

**Comment by clarle** [comment]
Removed unnecessary header detection in messenger.js so all responses now return "text/plain" content.

Brings test coverage up to 100% with removal.

File: test/messenger.js [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+            });
+        },
+        teardown: function (hub) {
+            hub.close();
+        },
+        "when a non-GET or HEAD request is used" : {
+            topic : function (hub) {
+                var vow = this;
+                var req = http.request({
+                    host : hub.server.address().address,
```
Comment (reid) [inline test/messenger.js]: Nitpicks:
1. Consolidate this into the previous var statement. Run `make lint` before committing to catch this kind of nitpick.
2. Call `hub.server.address()` once, assign to a var (say, `address`), then use it here.
3. I try to omit the space between `host` and `:` when it comes to object literals, but I'm also inconsistent about this. You don't need to change it, just when it comes to whitespace rules, follow the convention of the file you're in — it appears you're already doing that, since `messenger.js` used that kind of space.

File: lib/hub/index.js [hunk 2]
```diff
@@ -347,7 +347,7 @@ Hub.prototype._createServer = function (router) {
                 }
             },
             function lastResort(req, res) {
-                if (req.method !== "GET" || req.method !== "HEAD") {
+                if (req.method !== "GET" && req.method !== "HEAD") {
```
Comment (reid) [inline lib/hub/index.js:350]: Thanks for fixing this!

**Comment by reid** [comment]
Clarence,

Once you can run `make lint` without errors, this looks ready for merging. See comments above for lower priority feedback.

Reid
